# Site settings
title: Dan's Maddening Descent into Hobby Electronics
email: daniel@kulinski.net
description: > # this means to ignore newlines until "baseurl:"
  Dan's descent into DIY hobby electronics
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://overambitio.us" # the base hostname & protocol for your site
twitter_username: dkulinski

# Build settings
markdown: kramdown
