# Site settings
title: Dan's Maddening Descent into Electronic Design
email: daniel@kulinski.net
description: > # this means to ignore newlines until "baseurl:"
  Dan's descent into electronic design.  Using tools such as Arduino and Raspberry Pi.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://overambitio.us" # the base hostname & protocol for your site
twitter_username: dkulinski
destination: /var/www/overambitio.us

# Build settings
markdown: kramdown
